spring.application.name=integracao-alunos-spring

#--- Banco de Dados H2
#spring.datasource.url=jdbc:h2:file:./data/alunos-db;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

#--- Banco de Dados Oracle
#spring.datasource.url=jdbc:oracle:thin:@[HOST]:1521:ORCL
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true